/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      screens: {
        short: { raw: '(max-height: 860px)' },
        tall: { raw: '(min-height: 960px)' },
      },
      colors: {
        'ledger-bg': '#070b12',
        'ledger-sidebar': '#05080e',
        'ledger-shell': '#070b12',
        'ledger-card': '#0c1219',
        'ledger-card-alt': '#0e151e',
        'ledger-inset': '#111820',
        'ledger-well': '#111820',
        'ledger-track': '#1a2330',
        'ledger-hover': '#121a24',
        'ledger-active': '#151d28',
        'ledger-border': '#1a2330',
        'ledger-border-subtle': '#161e28',
        'ledger-border-input': '#243042',
        'ledger-border-strong': 'rgba(255,255,255,0.12)',
        'ledger-text-primary': '#f0f2f5',
        'ledger-text-heading': '#f7f8fa',
        'ledger-text-secondary': '#c5cbd4',
        'ledger-text-muted': '#8b95a5',
        'ledger-text-faint': '#6b7380',
        'ledger-text-faintest': '#565e6b',
        'ledger-accent': '#4d8dff',
        'ledger-accent-on': '#06101c',
        'ledger-accent-hover': '#6ba0ff',
        'ledger-accent-press': '#3b78e8',
        'ledger-accent-text': '#8eb6ff',
        'ledger-accent-soft': 'rgba(77,141,255,0.14)',
        'ledger-accent-border': 'rgba(77,141,255,0.32)',
        'ledger-positive': '#3dd68c',
        'ledger-positive-soft': 'rgba(61,214,140,0.12)',
        'ledger-positive-border': 'rgba(61,214,140,0.28)',
        'ledger-negative': '#ff6b7a',
        'ledger-negative-soft': 'rgba(255,107,122,0.12)',
        'ledger-negative-border': 'rgba(255,107,122,0.28)',
        'ledger-warning': '#e8b86d',
        'ledger-warning-soft': 'rgba(232,184,109,0.12)',
        'ledger-warning-border': 'rgba(232,184,109,0.28)',
        'ledger-cat-teal': '#4fc4c4',
        'ledger-cat-violet': '#8a7df0',
        'ledger-cat-green': '#3dd68c',
        'ledger-cat-slate': '#565c69',
      },
      fontFamily: {
        sans: ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'heronet': '44px',
        'stat': '28px',
        'title': '14px',
        'section': '14px',
        'micro': '10px',
        'label': '12px',
        'meta': '12px',
        'body': '13px',
      },
      letterSpacing: {
        'caps': '0.08em',
        'tightest': '-0.04em',
      },
      borderRadius: {
        'card': '12px',
        'btn': '8px',
        'pill': '6px',
        'avatar': '8px',
        'chip': '8px',
        'well': '10px',
        'shell': '0px',
      },
    },
  },
  darkMode: 'class',
  plugins: [],
}
